=== Mrkike/LenguajedeMarcas/Examen/Ejercicio3/factura_esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="NombreType">
        <xs:restriction base="xs:string">
            <xs:minLength value="5"/>
            <xs:maxLength value="30"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CIFType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}-[A-Z]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TelefonoType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{9}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoArticuloType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Libro"/>
            <xs:enumeration value="DVD"/>
            <xs:enumeration value="Varios"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Facturas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Factura" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Cliente">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nombre" type="NombreType"/>
                                        <xs:element name="CIF" type="CIFType"/>
                                        <xs:element name="Telefono" type="TelefonoType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Emisor">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nombre" type="NombreType"/>
                                        <xs:element name="CIF" type="CIFType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="DetalleFactura" maxOccurs="15">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Descripcion" type="NombreType"/>
                                    </xs:sequence>
                                    <xs:attribute name="CodigoArticulo" type="xs:string" use="required"/>
                                    <xs:attribute name="Tipo" type="TipoArticuloType" use="required"/>
                                    <xs:attribute name="Cantidad" type="xs:positiveInteger" use="required"/>
                                    <xs:attribute name="Importe" type="xs:decimal" use="required"/>
                                    <xs:attribute name="PVP" type="xs:decimal" use="required"/>
                                    <xs:attribute name="Oferta" type="xs:boolean" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="NumeroFactura" type="xs:positiveInteger" use="required"/>
                        <xs:attribute name="Fecha" type="xs:date" use="required"/>
                        <xs:attribute name="Moneda" type="xs:string" use="optional" default="â‚¬"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Mrkike/LenguajedeMarcas/Examen/Ejercicio3/facturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<Facturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="factura_esquema.xsd">
    <Factura NumeroFactura="1" Fecha="2024-12-10" Moneda="€">
        <Cliente>
            <Nombre>Juan Perez</Nombre>
            <CIF>12345678-A</CIF>
            <Telefono>600123456</Telefono>
        </Cliente>
        <Emisor>
            <Nombre>Empresa XYZ</Nombre>
            <CIF>87654321-B</CIF>
        </Emisor>
        <DetalleFactura CodigoArticulo="A001" Tipo="Libro" Cantidad="2" Importe="30.00" PVP="15.00" Oferta="true">
            <Descripcion>Libro de ficción</Descripcion>
        </DetalleFactura>
    </Factura>
    <Factura NumeroFactura="2" Fecha="2024-12-11">
        <Cliente>
            <Nombre>Maria Lopez</Nombre>
            <CIF>23456789-C</CIF>
            <Telefono>700987654</Telefono>
        </Cliente>
        <Emisor>
            <Nombre>Editorial ABC</Nombre>
            <CIF>54321678-D</CIF>
        </Emisor>
        <DetalleFactura CodigoArticulo="B002" Tipo="DVD" Cantidad="1" Importe="20.00" PVP="20.00">
            <Descripcion>Pelicula en Blu-Ray</Descripcion>
        </DetalleFactura>
    </Factura>
</Facturas>
