=== Mrkike/LenguajedeMarcas/ejemplo/Personas.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre, carnet, sexo, emails, parentesco?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT carnet (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT emails (email+)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT parentesco (padre?, hermano*)>
<!ELEMENT padre (#PCDATA)>
<!ELEMENT hermano (#PCDATA)>

<!ATTLIST persona
  carnet ID #REQUIRED
  sexo (Hombre | Mujer) #REQUIRED>

=== Mrkike/LenguajedeMarcas/ejemplo/Personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas>
    <persona carnet="B2548" sexo="Hombre">
        <nombre>Antonio Mart√≠nez</nombre>
        <emails>
            <email>antonio@gmail.com</email>
        </emails>
        <parentesco>
            <padre>B1111</padre>
            <padre>C2222</padre>
        </parentesco>
    </persona>
